
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramneek Kalra
 */
public class Book_Detail1 extends javax.swing.JFrame {

    /**
     * Creates new form Book_Detail
     */
    public Book_Detail1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        edit = new javax.swing.JTextField();
        pnp = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        pages = new javax.swing.JTextField();
        vol = new javax.swing.JTextField();
        source = new javax.swing.JTextField();
        bnd = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        bn = new javax.swing.JTextField();
        sub = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        remark = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        filter = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Book Details");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Logout");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Book Details"));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Search the Book:");

        b.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        b.setNextFocusableComponent(b);
        b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bFocusGained(evt);
            }
        });
        b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bKeyTyped(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Display");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Acc No:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Author:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Title:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Place and Publisher:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Pages:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Edition:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Year:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Volume:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("BillNo and Date:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Source:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Cost of Book (Rs.):");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Class No:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Book No:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Subject:");

        no.setEditable(false);
        no.setBackground(new java.awt.Color(255, 255, 255));
        no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        no.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        no.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        no.setRequestFocusEnabled(false);

        author.setEditable(false);
        author.setBackground(new java.awt.Color(255, 255, 255));
        author.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        author.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        author.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        author.setRequestFocusEnabled(false);

        title.setEditable(false);
        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        title.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        title.setRequestFocusEnabled(false);

        edit.setEditable(false);
        edit.setBackground(new java.awt.Color(255, 255, 255));
        edit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        edit.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        edit.setRequestFocusEnabled(false);

        pnp.setEditable(false);
        pnp.setBackground(new java.awt.Color(255, 255, 255));
        pnp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pnp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pnp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnp.setRequestFocusEnabled(false);

        year.setEditable(false);
        year.setBackground(new java.awt.Color(255, 255, 255));
        year.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        year.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        year.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        year.setRequestFocusEnabled(false);

        pages.setEditable(false);
        pages.setBackground(new java.awt.Color(255, 255, 255));
        pages.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pages.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pages.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pages.setRequestFocusEnabled(false);

        vol.setEditable(false);
        vol.setBackground(new java.awt.Color(255, 255, 255));
        vol.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        vol.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vol.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vol.setRequestFocusEnabled(false);

        source.setEditable(false);
        source.setBackground(new java.awt.Color(255, 255, 255));
        source.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        source.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        source.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        source.setRequestFocusEnabled(false);

        bnd.setEditable(false);
        bnd.setBackground(new java.awt.Color(255, 255, 255));
        bnd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bnd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bnd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bnd.setRequestFocusEnabled(false);

        cost.setEditable(false);
        cost.setBackground(new java.awt.Color(255, 255, 255));
        cost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cost.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cost.setRequestFocusEnabled(false);

        cn.setEditable(false);
        cn.setBackground(new java.awt.Color(255, 255, 255));
        cn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cn.setRequestFocusEnabled(false);

        bn.setEditable(false);
        bn.setBackground(new java.awt.Color(255, 255, 255));
        bn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        bn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bn.setRequestFocusEnabled(false);

        sub.setEditable(false);
        sub.setBackground(new java.awt.Color(255, 255, 255));
        sub.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sub.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sub.setRequestFocusEnabled(false);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Remarks:");

        remark.setEditable(false);
        remark.setBackground(new java.awt.Color(255, 255, 255));
        remark.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        remark.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        remark.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        remark.setRequestFocusEnabled(false);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Filter By:");

        filter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        filter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Author", "Title", "Subject" }));
        filter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Modify");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pages, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2))))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                                .addComponent(pnp))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(author, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                                    .addComponent(title))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(cn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(source, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vol, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cost)
                                    .addComponent(bnd, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sub)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(91, 91, 91)
                        .addComponent(remark)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("Back to Home");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int r=JOptionPane.showConfirmDialog(this, "Are you sure you want to Logout?");
        if(r==1){
            this.setVisible(false);
            this.setVisible(true);
        }
        else if(r==0){
            this.setVisible(false);
            Login_Page m=new Login_Page();
            JOptionPane.showMessageDialog(this, "You are successfully logged out!!");
            m.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bFocusGained

    private void bKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int str= Integer.parseInt(b.getText());
        String query="select* from master_book_record where Acc_No="+str;
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://172.16.31.50:3306/library","root","HMRITM");
            java.sql.Statement stmt=c.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                String nA=rs.getString("Acc_No");
                String nB=rs.getString("Author");
                String nC=rs.getString("Title");
                String nD=rs.getString("Edition");
                String nE=rs.getString("Place_Publishers");
                String nF=rs.getString("Year");
                String nG=rs.getString("Pages");
                String nH=rs.getString("Vol");
                String nI=rs.getString("Source");
                String nJ=rs.getString("BillNo_Date");
                String nK=rs.getString("Cost");
                String nL=rs.getString("Class_No");
                String nM=rs.getString("Book_No");
                String nN=rs.getString("Remarks");
                String nO=rs.getString("Subject");
                no.setText(nA);
                author.setText(nB);
                title.setText(nC);
                edit.setText(nD);
                pnp.setText(nE);
                year.setText(nF);
                pages.setText(nG);
                vol.setText(nH);
                source.setText(nI);
                bnd.setText(nJ);cost.setText(nK);
                cn.setText(nL);
                bn.setText(nM);remark.setText(nN);
                sub.setText(nO); 
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Main_Page m=new Main_Page();
        m.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(filter.getSelectedIndex()==1){
            String str= b.getText();
        String query="select* from master_book_record where Author like '%"+str+"%';";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://172.16.31.50:3306/library","root","HMRITM");
            java.sql.Statement stmt=c.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                String nA=rs.getString("Acc_No");
                String nB=rs.getString("Author");
                String nC=rs.getString("Title");
                String nD=rs.getString("Edition");
                String nE=rs.getString("Place_Publishers");
                String nF=rs.getString("Year");
                String nG=rs.getString("Pages");
                String nH=rs.getString("Vol");
                String nI=rs.getString("Source");
                String nJ=rs.getString("BillNo_Date");
                String nK=rs.getString("Cost");
                String nL=rs.getString("Class_No");
                String nM=rs.getString("Book_No");
                String nN=rs.getString("Remarks");
                String nO=rs.getString("Subject");
                no.setText(nA);
                author.setText(nB);
                title.setText(nC);
                edit.setText(nD);
                pnp.setText(nE);
                year.setText(nF);
                pages.setText(nG);
                vol.setText(nH);
                source.setText(nI);
                bnd.setText(nJ);cost.setText(nK);
                cn.setText(nL);
                bn.setText(nM);remark.setText(nN);
                sub.setText(nO); 
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
        else if(filter.getSelectedIndex()==2){
            String str= b.getText();
        String query="select* from master_book_record where Title like '%"+str+"%';";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://172.16.31.50:3306/library","root","HMRITM");
            java.sql.Statement stmt=c.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                String nA=rs.getString("Acc_No");
                String nB=rs.getString("Author");
                String nC=rs.getString("Title");
                String nD=rs.getString("Edition");
                String nE=rs.getString("Place_Publishers");
                String nF=rs.getString("Year");
                String nG=rs.getString("Pages");
                String nH=rs.getString("Vol");
                String nI=rs.getString("Source");
                String nJ=rs.getString("BillNo_Date");
                String nK=rs.getString("Cost");
                String nL=rs.getString("Class_No");
                String nM=rs.getString("Book_No");
                String nN=rs.getString("Remarks");
                String nO=rs.getString("Subject");
                no.setText(nA);
                author.setText(nB);
                title.setText(nC);
                edit.setText(nD);
                pnp.setText(nE);
                year.setText(nF);
                pages.setText(nG);
                vol.setText(nH);
                source.setText(nI);
                bnd.setText(nJ);cost.setText(nK);
                cn.setText(nL);
                bn.setText(nM);remark.setText(nN);
                sub.setText(nO); 
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
        else if(filter.getSelectedIndex()==3){
            String str= b.getText();
        String query="select* from master_book_record where Subject like '%"+str+"%';";
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection c=(Connection)
            DriverManager.getConnection("jdbc:mysql://172.16.31.50:3306/library","root","HMRITM");
            java.sql.Statement stmt=c.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            while(rs.next()){
                String nA=rs.getString("Acc_No");
                String nB=rs.getString("Author");
                String nC=rs.getString("Title");
                String nD=rs.getString("Edition");
                String nE=rs.getString("Place_Publishers");
                String nF=rs.getString("Year");
                String nG=rs.getString("Pages");
                String nH=rs.getString("Vol");
                String nI=rs.getString("Source");
                String nJ=rs.getString("BillNo_Date");
                String nK=rs.getString("Cost");
                String nL=rs.getString("Class_No");
                String nM=rs.getString("Book_No");
                String nN=rs.getString("Remarks");
                String nO=rs.getString("Subject");
                no.setText(nA);
                author.setText(nB);
                title.setText(nC);
                edit.setText(nD);
                pnp.setText(nE);
                year.setText(nF);
                pages.setText(nG);
                vol.setText(nH);
                source.setText(nI);
                bnd.setText(nJ);cost.setText(nK);
                cn.setText(nL);
                bn.setText(nM);remark.setText(nN);
                sub.setText(nO); 
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Detail1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField author;
    private javax.swing.JTextField b;
    private javax.swing.JTextField bn;
    private javax.swing.JTextField bnd;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField edit;
    private javax.swing.JComboBox<String> filter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField no;
    private javax.swing.JTextField pages;
    private javax.swing.JTextField pnp;
    private javax.swing.JTextField remark;
    private javax.swing.JTextField source;
    private javax.swing.JTextField sub;
    private javax.swing.JTextField title;
    private javax.swing.JTextField vol;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
